spring:
  application:
    name: VCS2
  jpa:
    hibernate:
      ddl-auto: validate

  datasource:
    url: jdbc:postgresql://localhost:5432/vcs2
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    default-schema: public
    change-log: classpath:/db/changelog/db.changelog-master.yaml
springdoc:
  show-login-endpoint: true
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  error:
    whitelabel:
      enabled: false
vcs:
  imageresourcepath:
    path: "/vcs"
microservice:
  url: http://localhost:8082

logging:
  file:
    name: logs/myapp.log
    path: logs
  level:
    root: INFO
