@baseUrl = http://localhost:8080

POST {{baseUrl}}/logout

###
GET {{baseUrl}}/password

###
//Забыл пароль, но неверный формат email
POST {{baseUrl}}/password
Content-Type: application/json

{
  "email": "hello"
}

###
//Забыл пароль, но такого email нет
POST {{baseUrl}}/password
Content-Type: application/json

{
  "email": "hello@gmail.com"
}

###
//Забыл пароль, и всё правильно
POST {{baseUrl}}/password
Content-Type: application/json

{
  "email": "banditxz76@gmail.com"
}

###
//Восстанавливаю пароль, но пишу неверный код
POST {{baseUrl}}/password/recovery
Content-Type: application/json

{
  "email": "banditxz76@gmail.com",
  "password": "123456",
  "code": "0562576"
}

###
//Восстанавливаю пароль, но пишу верный код
POST {{baseUrl}}/password/recovery
Content-Type: application/json

{
  "email": "banditxz76@gmail.com",
  "password": "123456",
  "code": "0562575"
}

###
//Логин со старым паролем
POST {{baseUrl}}/login?username=Vlad&password=12345

###
//Логин с новым паролем
# @no-redirect
POST {{baseUrl}}/login?username=Vlad&password=123456

